### PR TITLE
adjust stair top snap offset to 0

### PR DESCRIPTION
**Pull request by mudzereli**
is there a reason it shouldn't be 0?

### CODE REVIEW

**Comment by mudzereli** [comment]
also I was wondering, how did you get the snap points for every item? I was thinking of trying to add some items but wasn't sure if there's an easier way to figure out the snap points than just guessing/retrying a bunch of times to get it perfect.

**Comment by raymix** [comment]
Yeah, in-game models are built without measurement, confirmed by Sequisha - guy who made them. Stairs pivot is not properly centered to a model, too.
I am using modified lootpos tool made by awol, you can find it in DZEI repo, give yourself itemCitrine (or whatever else you want) to enable it. Once you select target and choose snap point, it will extract worldToModel coords to your local RPT file.
Skip trough this video to see me creating snaps:
http://www.twitch.tv/raymich/b/541559474

**Comment by mudzereli** [comment]
Awesome, thanks. I was wondering how you did it. that probably means i should adjust the bottom snap for the stair that I threw in.

**Comment by raymix** [comment]
Ah yeah, didn't check that. Don't rush with that one, you can see me fighting with stairs in last part of video, think I never actually got it perfect, but pretty close to "ok", lol.

**Pull request closed without merging**
